# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.channel_api import ChannelApi


class TestChannelApi(unittest.TestCase):
    """ChannelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelApi()

    def tearDown(self) -> None:
        pass

    def test_create_channel(self) -> None:
        """Test case for create_channel

        チャンネルを作成
        """
        pass

    def test_edit_channel(self) -> None:
        """Test case for edit_channel

        チャンネル情報を変更
        """
        pass

    def test_edit_channel_subscribers(self) -> None:
        """Test case for edit_channel_subscribers

        チャンネルの通知購読者を編集
        """
        pass

    def test_edit_channel_topic(self) -> None:
        """Test case for edit_channel_topic

        チャンネルトピックを編集
        """
        pass

    def test_get_channel(self) -> None:
        """Test case for get_channel

        チャンネル情報を取得
        """
        pass

    def test_get_channel_bots(self) -> None:
        """Test case for get_channel_bots

        チャンネル参加中のBOTのリストを取得
        """
        pass

    def test_get_channel_events(self) -> None:
        """Test case for get_channel_events

        チャンネルイベントのリストを取得
        """
        pass

    def test_get_channel_pins(self) -> None:
        """Test case for get_channel_pins

        チャンネルピンのリストを取得
        """
        pass

    def test_get_channel_stats(self) -> None:
        """Test case for get_channel_stats

        チャンネル統計情報を取得
        """
        pass

    def test_get_channel_subscribers(self) -> None:
        """Test case for get_channel_subscribers

        チャンネルの通知購読者のリストを取得
        """
        pass

    def test_get_channel_topic(self) -> None:
        """Test case for get_channel_topic

        チャンネルトピックを取得
        """
        pass

    def test_get_channel_viewers(self) -> None:
        """Test case for get_channel_viewers

        チャンネル閲覧者リストを取得
        """
        pass

    def test_get_channels(self) -> None:
        """Test case for get_channels

        チャンネルリストを取得
        """
        pass

    def test_get_messages(self) -> None:
        """Test case for get_messages

        チャンネルメッセージのリストを取得
        """
        pass

    def test_get_user_dm_channel(self) -> None:
        """Test case for get_user_dm_channel

        DMチャンネル情報を取得
        """
        pass

    def test_post_message(self) -> None:
        """Test case for post_message

        チャンネルにメッセージを投稿
        """
        pass

    def test_set_channel_subscribers(self) -> None:
        """Test case for set_channel_subscribers

        チャンネルの通知購読者を設定
        """
        pass


if __name__ == '__main__':
    unittest.main()
