# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notification_api import NotificationApi


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationApi()

    def tearDown(self) -> None:
        pass

    def test_edit_channel_subscribers(self) -> None:
        """Test case for edit_channel_subscribers

        チャンネルの通知購読者を編集
        """
        pass

    def test_get_channel_subscribers(self) -> None:
        """Test case for get_channel_subscribers

        チャンネルの通知購読者のリストを取得
        """
        pass

    def test_get_my_channel_subscriptions(self) -> None:
        """Test case for get_my_channel_subscriptions

        自分のチャンネル購読状態を取得
        """
        pass

    def test_get_my_unread_channels(self) -> None:
        """Test case for get_my_unread_channels

        未読チャンネルを取得
        """
        pass

    def test_get_my_view_states(self) -> None:
        """Test case for get_my_view_states

        自身のチャンネル閲覧状態一覧を取得
        """
        pass

    def test_read_channel(self) -> None:
        """Test case for read_channel

        チャンネルを既読にする
        """
        pass

    def test_register_fcm_device(self) -> None:
        """Test case for register_fcm_device

        FCMデバイスを登録
        """
        pass

    def test_set_channel_subscribe_level(self) -> None:
        """Test case for set_channel_subscribe_level

        チャンネル購読レベルを設定
        """
        pass

    def test_set_channel_subscribers(self) -> None:
        """Test case for set_channel_subscribers

        チャンネルの通知購読者を設定
        """
        pass

    def test_ws(self) -> None:
        """Test case for ws

        WebSocket通知ストリームに接続します
        """
        pass


if __name__ == '__main__':
    unittest.main()
