# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.file_api import FileApi


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        ファイルを削除
        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        ファイルをダウンロード
        """
        pass

    def test_get_file_meta(self) -> None:
        """Test case for get_file_meta

        ファイルメタを取得
        """
        pass

    def test_get_files(self) -> None:
        """Test case for get_files

        ファイルメタのリストを取得
        """
        pass

    def test_get_thumbnail_image(self) -> None:
        """Test case for get_thumbnail_image

        サムネイル画像を取得
        """
        pass

    def test_post_file(self) -> None:
        """Test case for post_file

        ファイルをアップロード
        """
        pass


if __name__ == '__main__':
    unittest.main()
