# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.o_auth2_response_type import OAuth2ResponseType

class TestOAuth2ResponseType(unittest.TestCase):
    """OAuth2ResponseType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2ResponseType(self):
        """Test OAuth2ResponseType"""
        # inst = OAuth2ResponseType()

if __name__ == '__main__':
    unittest.main()
