# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.o_auth2_prompt import OAuth2Prompt

class TestOAuth2Prompt(unittest.TestCase):
    """OAuth2Prompt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Prompt(self):
        """Test OAuth2Prompt"""
        # inst = OAuth2Prompt()

if __name__ == '__main__':
    unittest.main()
