# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_list import ChannelList

class TestChannelList(unittest.TestCase):
    """ChannelList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelList:
        """Test ChannelList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelList`
        """
        model = ChannelList()
        if include_optional:
            return ChannelList(
                public = [
                    openapi_client.models.channel.Channel(
                        id = '', 
                        parent_id = '', 
                        archived = True, 
                        force = True, 
                        topic = '', 
                        name = 'z', 
                        children = [
                            ''
                            ], )
                    ],
                dm = [
                    openapi_client.models.dm_channel.DMChannel(
                        id = '', 
                        user_id = '', )
                    ]
            )
        else:
            return ChannelList(
                public = [
                    openapi_client.models.channel.Channel(
                        id = '', 
                        parent_id = '', 
                        archived = True, 
                        force = True, 
                        topic = '', 
                        name = 'z', 
                        children = [
                            ''
                            ], )
                    ],
        )
        """

    def testChannelList(self):
        """Test ChannelList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
