# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bot_api import BotApi


class TestBotApi(unittest.TestCase):
    """BotApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BotApi()

    def tearDown(self) -> None:
        pass

    def test_activate_bot(self) -> None:
        """Test case for activate_bot

        BOTをアクティベート
        """
        pass

    def test_change_bot_icon(self) -> None:
        """Test case for change_bot_icon

        BOTのアイコン画像を変更
        """
        pass

    def test_connect_bot_ws(self) -> None:
        """Test case for connect_bot_ws

        WebSocket Mode BOT用通知ストリームに接続します
        """
        pass

    def test_create_bot(self) -> None:
        """Test case for create_bot

        BOTを作成
        """
        pass

    def test_delete_bot(self) -> None:
        """Test case for delete_bot

        BOTを削除
        """
        pass

    def test_edit_bot(self) -> None:
        """Test case for edit_bot

        BOT情報を変更
        """
        pass

    def test_get_bot(self) -> None:
        """Test case for get_bot

        BOT情報を取得
        """
        pass

    def test_get_bot_icon(self) -> None:
        """Test case for get_bot_icon

        BOTのアイコン画像を取得
        """
        pass

    def test_get_bot_logs(self) -> None:
        """Test case for get_bot_logs

        BOTのイベントログを取得
        """
        pass

    def test_get_bots(self) -> None:
        """Test case for get_bots

        BOTリストを取得
        """
        pass

    def test_get_channel_bots(self) -> None:
        """Test case for get_channel_bots

        チャンネル参加中のBOTのリストを取得
        """
        pass

    def test_inactivate_bot(self) -> None:
        """Test case for inactivate_bot

        BOTをインアクティベート
        """
        pass

    def test_let_bot_join_channel(self) -> None:
        """Test case for let_bot_join_channel

        BOTをチャンネルに参加させる
        """
        pass

    def test_let_bot_leave_channel(self) -> None:
        """Test case for let_bot_leave_channel

        BOTをチャンネルから退出させる
        """
        pass

    def test_reissue_bot(self) -> None:
        """Test case for reissue_bot

        BOTのトークンを再発行
        """
        pass


if __name__ == '__main__':
    unittest.main()
