# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_subscribe_level import ChannelSubscribeLevel

class TestChannelSubscribeLevel(unittest.TestCase):
    """ChannelSubscribeLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelSubscribeLevel(self):
        """Test ChannelSubscribeLevel"""
        # inst = ChannelSubscribeLevel()

if __name__ == '__main__':
    unittest.main()
