# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_my_fcm_device_request import PostMyFCMDeviceRequest

class TestPostMyFCMDeviceRequest(unittest.TestCase):
    """PostMyFCMDeviceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostMyFCMDeviceRequest:
        """Test PostMyFCMDeviceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostMyFCMDeviceRequest`
        """
        model = PostMyFCMDeviceRequest()
        if include_optional:
            return PostMyFCMDeviceRequest(
                token = 'bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1'
            )
        else:
            return PostMyFCMDeviceRequest(
                token = 'bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1',
        )
        """

    def testPostMyFCMDeviceRequest(self):
        """Test PostMyFCMDeviceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
