# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_get_my_external_accounts(self) -> None:
        """Test case for get_my_external_accounts

        外部ログインアカウント一覧を取得
        """
        pass

    def test_get_my_sessions(self) -> None:
        """Test case for get_my_sessions

        自分のログインセッションリストを取得
        """
        pass

    def test_link_external_account(self) -> None:
        """Test case for link_external_account

        外部ログインアカウントを紐付ける
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        ログイン
        """
        pass

    def test_logout(self) -> None:
        """Test case for logout

        ログアウト
        """
        pass

    def test_revoke_my_session(self) -> None:
        """Test case for revoke_my_session

        セッションを無効化
        """
        pass

    def test_unlink_external_account(self) -> None:
        """Test case for unlink_external_account

        外部ログインアカウントの紐付けを解除
        """
        pass


if __name__ == '__main__':
    unittest.main()
