# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webrtc_api import WebrtcApi


class TestWebrtcApi(unittest.TestCase):
    """WebrtcApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebrtcApi()

    def tearDown(self) -> None:
        pass

    def test_get_web_rtc_state(self) -> None:
        """Test case for get_web_rtc_state

        WebRTC状態を取得
        """
        pass

    def test_post_web_rtc_authenticate(self) -> None:
        """Test case for post_web_rtc_authenticate

        Skyway用認証API
        """
        pass


if __name__ == '__main__':
    unittest.main()
