# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.thumbnail_type import ThumbnailType

class TestThumbnailType(unittest.TestCase):
    """ThumbnailType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThumbnailType(self):
        """Test ThumbnailType"""
        # inst = ThumbnailType()

if __name__ == '__main__':
    unittest.main()
