# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activity_api import ActivityApi


class TestActivityApi(unittest.TestCase):
    """ActivityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivityApi()

    def tearDown(self) -> None:
        pass

    def test_get_activity_timeline(self) -> None:
        """Test case for get_activity_timeline

        アクテビティタイムラインを取得
        """
        pass

    def test_get_online_users(self) -> None:
        """Test case for get_online_users

        オンラインユーザーリストを取得
        """
        pass


if __name__ == '__main__':
    unittest.main()
