# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_client200_response import GetClient200Response

class TestGetClient200Response(unittest.TestCase):
    """GetClient200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClient200Response:
        """Test GetClient200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClient200Response`
        """
        model = GetClient200Response()
        if include_optional:
            return GetClient200Response(
                id = '',
                name = '0',
                description = '',
                developer_id = '',
                scopes = [
                    'read'
                    ],
                callback_url = '',
                secret = ''
            )
        else:
            return GetClient200Response(
                id = '',
                name = '0',
                description = '',
                developer_id = '',
                scopes = [
                    'read'
                    ],
                callback_url = '',
                secret = '',
        )
        """

    def testGetClient200Response(self):
        """Test GetClient200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
