# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.o_auth2_scope import OAuth2Scope

class TestOAuth2Scope(unittest.TestCase):
    """OAuth2Scope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Scope(self):
        """Test OAuth2Scope"""
        # inst = OAuth2Scope()

if __name__ == '__main__':
    unittest.main()
