# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bot_mode import BotMode

class TestBotMode(unittest.TestCase):
    """BotMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBotMode(self):
        """Test BotMode"""
        # inst = BotMode()

if __name__ == '__main__':
    unittest.main()
