# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bot_user import BotUser

class TestBotUser(unittest.TestCase):
    """BotUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BotUser:
        """Test BotUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BotUser`
        """
        model = BotUser()
        if include_optional:
            return BotUser(
                id = '',
                bot_user_id = ''
            )
        else:
            return BotUser(
                id = '',
                bot_user_id = '',
        )
        """

    def testBotUser(self):
        """Test BotUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
