# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_channel_request import PostChannelRequest

class TestPostChannelRequest(unittest.TestCase):
    """PostChannelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostChannelRequest:
        """Test PostChannelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostChannelRequest`
        """
        model = PostChannelRequest()
        if include_optional:
            return PostChannelRequest(
                name = 'z',
                parent = ''
            )
        else:
            return PostChannelRequest(
                name = 'z',
                parent = '',
        )
        """

    def testPostChannelRequest(self):
        """Test PostChannelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
