# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_detail import UserDetail

class TestUserDetail(unittest.TestCase):
    """UserDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDetail:
        """Test UserDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDetail`
        """
        model = UserDetail()
        if include_optional:
            return UserDetail(
                id = '',
                state = 0,
                bot = True,
                icon_file_id = '',
                display_name = '',
                name = 'zBAMDTMv2D2ylmgd10Z3UB6U',
                twitter_id = 'HqXzyCBw3_u',
                last_online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    openapi_client.models.user_tag.UserTag(
                        tag_id = '', 
                        tag = '', 
                        is_locked = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                groups = [
                    ''
                    ],
                bio = '',
                home_channel = ''
            )
        else:
            return UserDetail(
                id = '',
                state = 0,
                bot = True,
                icon_file_id = '',
                display_name = '',
                name = 'zBAMDTMv2D2ylmgd10Z3UB6U',
                twitter_id = 'HqXzyCBw3_u',
                last_online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    openapi_client.models.user_tag.UserTag(
                        tag_id = '', 
                        tag = '', 
                        is_locked = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                groups = [
                    ''
                    ],
                bio = '',
                home_channel = '',
        )
        """

    def testUserDetail(self):
        """Test UserDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
