# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_web_rtc_authenticate_request import PostWebRTCAuthenticateRequest

class TestPostWebRTCAuthenticateRequest(unittest.TestCase):
    """PostWebRTCAuthenticateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWebRTCAuthenticateRequest:
        """Test PostWebRTCAuthenticateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWebRTCAuthenticateRequest`
        """
        model = PostWebRTCAuthenticateRequest()
        if include_optional:
            return PostWebRTCAuthenticateRequest(
                peer_id = ''
            )
        else:
            return PostWebRTCAuthenticateRequest(
                peer_id = '',
        )
        """

    def testPostWebRTCAuthenticateRequest(self):
        """Test PostWebRTCAuthenticateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
