# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.thumbnail_info import ThumbnailInfo

class TestThumbnailInfo(unittest.TestCase):
    """ThumbnailInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThumbnailInfo:
        """Test ThumbnailInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThumbnailInfo`
        """
        model = ThumbnailInfo()
        if include_optional:
            return ThumbnailInfo(
                type = 'image',
                mime = '',
                width = 56,
                height = 56
            )
        else:
            return ThumbnailInfo(
                type = 'image',
                mime = '',
        )
        """

    def testThumbnailInfo(self):
        """Test ThumbnailInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
