# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.oidc_traq_user_info import OIDCTraqUserInfo

class TestOIDCTraqUserInfo(unittest.TestCase):
    """OIDCTraqUserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OIDCTraqUserInfo:
        """Test OIDCTraqUserInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OIDCTraqUserInfo`
        """
        model = OIDCTraqUserInfo()
        if include_optional:
            return OIDCTraqUserInfo(
                bio = '',
                groups = [
                    ''
                    ],
                tags = [
                    openapi_client.models.user_tag.UserTag(
                        tag_id = '', 
                        tag = '', 
                        is_locked = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                last_online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                twitter_id = 'HqXzyC',
                display_name = '',
                icon_file_id = '',
                bot = True,
                state = 0,
                permissions = [
                    'get_webhook'
                    ],
                home_channel = ''
            )
        else:
            return OIDCTraqUserInfo(
                bio = '',
                groups = [
                    ''
                    ],
                tags = [
                    openapi_client.models.user_tag.UserTag(
                        tag_id = '', 
                        tag = '', 
                        is_locked = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                last_online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                twitter_id = 'HqXzyC',
                display_name = '',
                icon_file_id = '',
                bot = True,
                state = 0,
                permissions = [
                    'get_webhook'
                    ],
                home_channel = '',
        )
        """

    def testOIDCTraqUserInfo(self):
        """Test OIDCTraqUserInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
