# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_view_state import ChannelViewState

class TestChannelViewState(unittest.TestCase):
    """ChannelViewState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelViewState(self):
        """Test ChannelViewState"""
        # inst = ChannelViewState()

if __name__ == '__main__':
    unittest.main()
