# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.message_api import MessageApi


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageApi()

    def tearDown(self) -> None:
        pass

    def test_add_message_stamp(self) -> None:
        """Test case for add_message_stamp

        スタンプを押す
        """
        pass

    def test_create_pin(self) -> None:
        """Test case for create_pin

        ピン留めする
        """
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        メッセージを削除
        """
        pass

    def test_edit_message(self) -> None:
        """Test case for edit_message

        メッセージを編集
        """
        pass

    def test_get_direct_messages(self) -> None:
        """Test case for get_direct_messages

        ダイレクトメッセージのリストを取得
        """
        pass

    def test_get_message(self) -> None:
        """Test case for get_message

        メッセージを取得
        """
        pass

    def test_get_message_clips(self) -> None:
        """Test case for get_message_clips

        自分のクリップを取得
        """
        pass

    def test_get_message_stamps(self) -> None:
        """Test case for get_message_stamps

        メッセージのスタンプリストを取得
        """
        pass

    def test_get_messages(self) -> None:
        """Test case for get_messages

        チャンネルメッセージのリストを取得
        """
        pass

    def test_get_pin(self) -> None:
        """Test case for get_pin

        ピン留めを取得
        """
        pass

    def test_post_direct_message(self) -> None:
        """Test case for post_direct_message

        ダイレクトメッセージを送信
        """
        pass

    def test_post_message(self) -> None:
        """Test case for post_message

        チャンネルにメッセージを投稿
        """
        pass

    def test_remove_message_stamp(self) -> None:
        """Test case for remove_message_stamp

        スタンプを消す
        """
        pass

    def test_remove_pin(self) -> None:
        """Test case for remove_pin

        ピン留めを外す
        """
        pass

    def test_search_messages(self) -> None:
        """Test case for search_messages

        メッセージを検索
        """
        pass


if __name__ == '__main__':
    unittest.main()
