# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_bot200_response import GetBot200Response

class TestGetBot200Response(unittest.TestCase):
    """GetBot200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBot200Response:
        """Test GetBot200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBot200Response`
        """
        model = GetBot200Response()
        if include_optional:
            return GetBot200Response(
                id = '',
                bot_user_id = '',
                description = '',
                developer_id = '',
                subscribe_events = [
                    ''
                    ],
                mode = 'HTTP',
                state = 0,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tokens = openapi_client.models.bot_tokens.BotTokens(
                    verification_token = '', 
                    access_token = '', ),
                endpoint = '',
                privileged = True,
                channels = [
                    ''
                    ]
            )
        else:
            return GetBot200Response(
                id = '',
                bot_user_id = '',
                description = '',
                developer_id = '',
                subscribe_events = [
                    ''
                    ],
                mode = 'HTTP',
                state = 0,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tokens = openapi_client.models.bot_tokens.BotTokens(
                    verification_token = '', 
                    access_token = '', ),
                endpoint = '',
                privileged = True,
                channels = [
                    ''
                    ],
        )
        """

    def testGetBot200Response(self):
        """Test GetBot200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
